server:
  port: 8080

spring:
  # Cấu hình Database SQL Server Local
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=QL_TiemBanh;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true 
    username: sa # Thay bằng username SQL Server của bạn
    password: 123456 # Thay bằng password thực tế của bạn
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update # Tự động tạo/cập nhật bảng dựa trên Entity
    show-sql: true # Bật cái này lên để thấy câu lệnh SQL chạy ngầm, rất dễ debug

  # Cấu hình Redis Local
  data:
    redis:
      host: localhost
      port: 6379

  # TÀI KHOẢN GỬI MAIL (CHỈ DÙNG Ở DEV)
  mail:
    username: vegetableshop88@gmail.com # ĐIỀN EMAIL CỦA BẠN VÀO ĐÂY
    password: "ixsakgqijctydtlo" # ĐIỀN MẬT KHẨU ỨNG DỤNG GMAIL 16 KÝ TỰ VÀO ĐÂY

# [ĐÃ SỬA]: Đưa sepay ra ngoài cùng cấp gốc (bằng cấp với server và spring)
sepay:
  webhook-token: "PolyCakeSecured2026"