server:
  port: 8081 # Đổi port để không đụng với lúc đang code (dev)

spring:
  # Khi Test thường dùng database ảo (H2 in-memory) chạy trên RAM cho lẹ và không rác data thật
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # Chạy test xong thì tự động xóa sạch bảng